# Linux build configuration for Travis CI

sudo: required

os:
  - linux

# Travis CI is powered with Ubuntu 12.04, whose toolchain is outdated.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - gcc-4.9
      - g++-4.9
      - clang-3.6
      - ninja-build
      - lcov

before_install:
  - ./InstallPackagesAndConfig.sh

script:
  - ./test.sh
